// AUTO-GENERATED by scripts/gen-carousel.mjs — do not edit by hand.
// Regenerated on every `npm run dev` and `npm run build`.

export const carouselRow1: string[] = [
  "/carousel/000026640003.JPG",
  "/carousel/000026640009.JPG",
  "/carousel/DSC02185.jpeg",
  "/carousel/DSC02218.jpeg",
  "/carousel/DSC04801.jpeg",
  "/carousel/DSC05296.JPG"
];

export const carouselRow2: string[] = [
  "/carousel/DSC05460.JPG",
  "/carousel/DSC05511.JPG",
  "/carousel/DSC06293.JPG",
  "/carousel/DSC07599.JPG",
  "/carousel/DSC07955.jpeg",
  "/carousel/IMG_0176.jpeg"
];

export const carouselRow3: string[] = [
  "/carousel/IMG_1884.jpeg",
  "/carousel/IMG_2769.jpeg",
  "/carousel/IMG_3095.JPG",
  "/carousel/IMG_3326.jpeg",
  "/carousel/IMG_5142.JPG",
  "/carousel/ORG_DSC04599.JPG"
];
