// AUTO-GENERATED by scripts/gen-carousel.mjs — do not edit by hand.
// Regenerated on every `npm run dev` and `npm run build`.

export type CarouselImage = {
  src: string;
  width: number;
  height: number;
};

export const carouselRow1: CarouselImage[] = [
  {
    "src": "/carousel/000026640003.JPG",
    "width": 397,
    "height": 600
  },
  {
    "src": "/carousel/000026640009.JPG",
    "width": 397,
    "height": 600
  },
  {
    "src": "/carousel/DSC02185.jpeg",
    "width": 600,
    "height": 400
  },
  {
    "src": "/carousel/DSC02218.jpeg",
    "width": 600,
    "height": 400
  },
  {
    "src": "/carousel/DSC04801.jpeg",
    "width": 400,
    "height": 600
  },
  {
    "src": "/carousel/DSC05296.JPG",
    "width": 400,
    "height": 600
  }
];

export const carouselRow2: CarouselImage[] = [
  {
    "src": "/carousel/DSC05460.JPG",
    "width": 400,
    "height": 600
  },
  {
    "src": "/carousel/DSC05511.JPG",
    "width": 400,
    "height": 600
  },
  {
    "src": "/carousel/DSC06293.JPG",
    "width": 600,
    "height": 400
  },
  {
    "src": "/carousel/DSC07599.JPG",
    "width": 400,
    "height": 600
  },
  {
    "src": "/carousel/DSC07955.jpeg",
    "width": 400,
    "height": 600
  },
  {
    "src": "/carousel/IMG_0176.jpeg",
    "width": 450,
    "height": 600
  }
];

export const carouselRow3: CarouselImage[] = [
  {
    "src": "/carousel/IMG_1884.jpeg",
    "width": 450,
    "height": 600
  },
  {
    "src": "/carousel/IMG_2769.jpeg",
    "width": 600,
    "height": 450
  },
  {
    "src": "/carousel/IMG_3095.JPG",
    "width": 338,
    "height": 600
  },
  {
    "src": "/carousel/IMG_3326.jpeg",
    "width": 450,
    "height": 600
  },
  {
    "src": "/carousel/IMG_5142.JPG",
    "width": 600,
    "height": 400
  },
  {
    "src": "/carousel/ORG_DSC04599.JPG",
    "width": 400,
    "height": 600
  }
];
